spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "software-security-lab-1"
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  jwt:
    life-time: 3600000  # ms
    secret: ${SECRET}